### ISSUE TITLE
Not logging data into influxdb

### ISSUE THREAD

**Issue by Amalokch** [ratibor78/srvstatus#16]
Hello guys, I am new to telegraf and in general to the IT world. I am more use to low-end programming languages, but have accomplish many things though which make me proud.
Probably my issue is something dumb :-), but I don't know if I am missing something or what because I followed the process example shown here but it seems is not logging the data into influxdb.

I even ran the the python script manually and is working as you can see in the screenshot below:
![Screen Shot 2022-04-28 at 10 30 52](https://user-images.githubusercontent.com/69423323/165691329-a05757e2-87e8-42fd-a064-ba5856f673c0.png)
 
From grafana I can see the panels are pointing out to a measurement called "services_stats"
![Screen Shot 2022-04-28 at 10 34 15](https://user-images.githubusercontent.com/69423323/165691761-8f50f1c8-2897-4eae-9873-cb240e911a25.png)

And actually I looked into the influx CLI and the measurement is not there.

If you are wondering this is my Telegraf plugin exec file.... exactly the same:
![Screen Shot 2022-04-28 at 10 38 27](https://user-images.githubusercontent.com/69423323/165692239-b2d8e424-c68c-43d7-8359-af6335bab524.png)

Telegraf is running, I even changed the "data_format" to Influx to see what happens and nothing.

I think the python script is not logging the data into influxdb, because probably doesn't know in which database should store the data (I have many influxdb databases).

So yeah, I hope it makes sense and you can help me with this. Regards!

**Comment by ratibor78** [comment]
Hi, sorry for the late response, it is a war that happens in my country, so I was not able to reply, but now all is OK and I'm safe and have free time, so do you need any help with that ?

**Comment by ratibor78** [comment]
No reply there so I'll close it for now
