### ISSUE TITLE
problem when getting status of user service

### ISSUE THREAD

**Issue by hsnuhayato** [ratibor78/srvstatus#17]
Hi, I really like this project. 
However, when I run telegraf in local as:
```bash
$ sudo systemctl start telegraf
```
Then telegraf was started by user "telegraf".
As a result, telegraf was not able to get services started by other by this line in service.py
```py
out = subprocess.Popen(["systemctl", "--user", "status", service], stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)  # NOQA
```

Do you have any idea about this problem?
Thanks advance

**Comment by ratibor78** [comment]
Hi @hsnuhayato, I'll try to reproduce this tomorrow, and will see. I guess the problem is in privileges user telegraf may not have rights to access some files, but will check this.
