### ISSUE TITLE
[Question] Python3 support

### ISSUE THREAD

**Issue by smihajlovic-frame** [ratibor78/srvstatus#6]
Hello, we're using this code for some time and so far it's been amazing.

We're also transitioning to using Python3 everywhere and I'm interested in whether this would work with Python3? Has it been tested?

Thanks!

**Comment by b4b857f6ee** [comment]
Yes i have use it with 3.6 :)

**Comment by ratibor78** [comment]
Hi, I'll rewrite and test that code on Python3 soon. Stay in touch ;)
