### ISSUE TITLE
Service status grafana dashboard not working the python script works data is getting pushed to influx

### ISSUE THREAD

**Issue by sanfx** [ratibor78/srvstatus#8]
In my grafana service_status.json when imported is showing nothing.

I ran your python script it does give output and I then laters checked in the influx db so data is there then why  
even after selecting the correct  and only influxDb and only host rockpi then why grafana dashboard  status is not working. 

```
time                host   service                status status_time
----                ----   -------                ------ -----------
1596393690000000000 rockpi docker.service         1      71104
1596393690000000000 rockpi grafana-server.service 1      5536
1596393690000000000 rockpi influxdb.service       1      1937
1596393690000000000 rockpi prometheus.service     1      5500
1596393690000000000 rockpi telegraf.service       1      10
1596393700000000000 rockpi docker.service         1      71114
1596393700000000000 rockpi grafana-server.service 1      5546
1596393700000000000 rockpi influxdb.service       1      1947
1596393700000000000 rockpi prometheus.service     1      5510
1596393700000000000 rockpi telegraf.service       1      20
```

Can you please show me what are the settings for influxDB data source or if anythong I need to change in the `service_status.json` after importing to grafana ?

**Comment by ratibor78** [comment]
Sorry for the late response, I'll check it soon.

**Comment by ratibor78** [comment]
Hi once more, if you have the all needed data in InfluxDB, this means the script and telegraf working ON, so you need to figure out how to use Influxdb with Grafana, please add the data source with your InfluxDb into Grafana first, and then install my example dashboard, then type edit on any of service and look how the request must be done.
