### ISSUE TITLE
Grafana Dashboard Telegraf new

### ISSUE THREAD

**Issue by b4b857f6ee** [ratibor78/srvstatus#9]
Hello,

Thank you for your awesome script. I have modify some things and made Grafana Dashboard :)

Maybe you can like it!

https://grafana.com/grafana/dashboards/13309

**Comment by ratibor78** [comment]
Thanka @b4b857f6ee, I'll check it and add it to this repo ! Thanks once more !

**Comment by b4b857f6ee** [comment]
> !

You're very welcome.
I made some change in local but i don't remember if i have commit it yet.
I will check later.
I have done something like but for FreeBSD and a specific app if someone looking for FreeBSD : https://grafana.com/grafana/dashboards/13310

**Comment by ratibor78** [comment]
Looks very good !

**Comment by ratibor78** [comment]
I added the link to your dashboard to my project documentation, thanks!
